### ISSUE TITLE
Unable to find own profile ID, nor web feeds

### ISSUE THREAD

**Issue by fedebarusco** [isaac-chung/strava-kudos#16]
## Description

I'm encountering an issue with the script (Playwright version pinned in `requirements.txt`). 
While the script successfully logs in, it fails to:
1. **Retrieve the user's own profile ID**
2. **Access web feeds after manually setting the profile ID**

It seems these problems are **not dependent** as manually setting the profile ID doesn't resolve the web feed issue.

## Steps to Reproduce

1. Run the script locally or through GitHub actions.
2. Observe the script successfully logging in to Strava.
3. Verify the script fails to retrieve the user's own profile ID.
4. **Optional:**
    - Manually set the profile ID in the script.
    - Observe the script still fails to access web feeds.

## Expected Behavior

1. The script retrieves the user's own profile ID after successful login.
2. After login (or with a manually set profile ID), the script successfully retrieves and processes web feeds.

## System Information

- Python Version: (both 3.11 and 3.12)
- Playwright Version: (pinned in `requirements.txt`)

**Comment by fedebarusco** [comment]
The script's inability to find the profile ID and access web feeds was due to the password, not an actual bug.

Suggestion: I'd recommend improving the login step to provide more informative error messages when passwords are incorrect! Implementing such improvements would enhance user experience and make troubleshooting easier.

Thank you for bringing this to attention!

**Comment by isaac-chung** [comment]
Hey @fedebarusco, thanks for the feedback. Feel free to open a PR for this issue.
