### ISSUE TITLE
no web feeds found, no kudos given....

### ISSUE THREAD

**Issue by zuselli84** [isaac-chung/strava-kudos#17]
Hi, 

I just installed your script and could finally run it... 
But It gives the following response: 
```

python3 give_kudos.py
---Logged in!!---
id xxxxx
web feeds found: 0

Kudos given: 0
```

Even the feed has open activities to give kudos....
Am I doing something wrong?

**Comment by isaac-chung** [comment]
Hi @zuselli84, 

my latest run 21 minutes ago gave back the following:
```
Run python give_kudos.py
---Logged in!!---
id xxxxxxxx
web feeds found: 100
==c====c====c==c====c===========================================================
Kudos given: 75
```

My experience was that if you could log in, but no feeds was found, the browser could be the culprit, but it could also be something else
Would you be able to share some more details on your setup?

**Comment by zuselli84** [comment]
hi @isaac-chung Thank you very much for your reply. 

I didn't change your script, so it should youse firefox. 
Its version: 
Mozilla Firefox 124.0.1

my setup is a ubuntu server, what kind of information is required for debugging? And how can i check if the browser is the culprit?

**Comment by isaac-chung** [comment]
Mine runs via Github Actions on Ubuntu 20.04.6. 
Previously, I have done some debugging by getting screenshots to check if the feed page was loaded in time. This is done by calling `self.page.screenshot("/out/path.png")`. 

Separately, I wonder if you're able to set up this run in Github Actions for your fork?

**Comment by zuselli84** [comment]
Thanks for the debugging hint. 
my Ubuntu is: 
Description:    Ubuntu 22.04.4 LTS
Do you think that could be the reason? 

Unfortunately I don't know how to run it in Github Actions....

**Comment by zuselli84** [comment]
i could manage to run it with Github Actions, but I'm not sure, if I set the environment variables correct:

python give_kudos.py
  shell: /usr/bin/bash -e {0}
  env:
    STRAVA_EMAIL: 
    STRAVA_PASSWORD: 
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/zuselli84/strava-kudos/actions/runs/8680663851/job/23801736130#step:6:3).9.10/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.10/x6[4](https://github.com/zuselli84/strava-kudos/actions/runs/8680663851/job/23801736130#step:6:4)/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.10/x[6](https://github.com/zuselli84/strava-kudos/actions/runs/8680663851/job/23801736130#step:6:6)4
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.10/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.[9](https://github.com/zuselli84/strava-kudos/actions/runs/8680663851/job/23801736130#step:6:9).10/x64/lib
---Logged in!!---
can't find own profile ID
web feeds found: 0

Kudos given: 0

Now it responds with "can't find own profile ID"

**Comment by isaac-chung** [comment]
The difference in versions can be a potential cause. I'm unfamiliar with that unfortunately. 

Looking at your print out, the env vars should have *** printed beside them. Did you add them to "repository secrets"? (Settings -> Security -> Secrets and Variables -> Actions)

**Comment by zuselli84** [comment]
That was it, I habe entered the secrets in the wrong place. 
Now this worked.... 
Thanks for your support.
I'm wondering, why this is not working on my own Ubuntu Server. That would be very cool, if I could run this on my server.... 
Do you think this is tricky to debug?

**Comment by zuselli84** [comment]
@isaac-chung I changed versions in Github workflow, so that it's the same as my server: 
ubuntu 22.04
python: 3.10.12

in Github action, it works fine... 
Are there other things to consider e.g. Firefox? Or does playwright includes correct firefox version?

**Comment by isaac-chung** [comment]
Great! Glad you got that sorted out. As for Firefox version, the `playwright install` command should install this version:
```
Downloading Firefox 108.0.2 (playwright build v1372) from https://playwright.azureedge.net/builds/firefox/1372/firefox-ubuntu-20.04.zip
```

**Comment by zuselli84** [comment]
Do I understand it correct, that the Firefox on the host system does not influence your skript. 
I use same Playwright version 1.30.0, so it should use correct browser..(?)

**Comment by zuselli84** [comment]
It works, there was an issue with playwright, I uninstalled it and re-installed it according GH workflow.. Now it works. 
Thank you for your help
