### ISSUE TITLE
script fails after retries

### ISSUE THREAD

**Issue by feamster** [isaac-chung/strava-kudos#9]
no kudos are given, script basically times out after retries.

error started showing up recently, maybe this week?

**Comment by isaac-chung** [comment]
In general, it would be very helpful 
- before raising an issue: See if you had updated the fork.
- when raising an issue: include some basic details, such as which line is specifically timing out (can be found in the logs) and some hints to help others to reproduce your issue.

**Comment by isaac-chung** [comment]
Closing this issue for now due to inactivity. Feel free to reopen to add any details requested above.
